// Code generated by github.com/blakewilliams/overtime DO NOT EDIT

package overtime

import (
	"net/http"
)

type Controller interface {
	GetCommentByID(w http.ResponseWriter, r *http.Request) (*Comment, error)
	GetPostByID(w http.ResponseWriter, r *http.Request) (*Post, error)
}
